// Code generated by mockery v2.7.4. DO NOT EDIT.

package bus

import (
	context "context"

	event "github.com/peteqproj/peteq/pkg/event"
	mock "github.com/stretchr/testify/mock"
)

// MockEventStorage is an autogenerated mock type for the EventStorage type
type MockEventStorage struct {
	mock.Mock
}

// Persist provides a mock function with given fields: _a0, _a1
func (_m *MockEventStorage) Persist(_a0 context.Context, _a1 event.Event) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Event) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
