// Code generated by mockery v2.7.4. DO NOT EDIT.

package bus

import (
	context "context"

	event "github.com/peteqproj/peteq/pkg/event"
	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, ev
func (_m *MockEventPublisher) Publish(ctx context.Context, ev event.Event) (string, error) {
	ret := _m.Called(ctx, ev)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, event.Event) string); ok {
		r0 = rf(ctx, ev)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, event.Event) error); ok {
		r1 = rf(ctx, ev)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
