// Code generated by mockery v2.5.1. DO NOT EDIT.

package bus

import (
	handler "github.com/peteqproj/peteq/pkg/event/handler"
	mock "github.com/stretchr/testify/mock"
)

// MockEventWatcher is an autogenerated mock type for the EventWatcher type
type MockEventWatcher struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *MockEventWatcher) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *MockEventWatcher) Stop() {
	_m.Called()
}

// Subscribe provides a mock function with given fields: name, _a1
func (_m *MockEventWatcher) Subscribe(name string, _a1 handler.EventHandler) {
	_m.Called(name, _a1)
}
