// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package view

import (
	gin "github.com/gin-gonic/gin"
	handler "github.com/peteqproj/peteq/pkg/event/handler"
	mock "github.com/stretchr/testify/mock"
)

// MockView is an autogenerated mock type for the View type
type MockView struct {
	mock.Mock
}

// EventHandlers provides a mock function with given fields:
func (_m *MockView) EventHandlers() map[string]handler.EventHandler {
	ret := _m.Called()

	var r0 map[string]handler.EventHandler
	if rf, ok := ret.Get(0).(func() map[string]handler.EventHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]handler.EventHandler)
		}
	}

	return r0
}

// Get provides a mock function with given fields: c
func (_m *MockView) Get(c *gin.Context) {
	_m.Called(c)
}
