// Code generated by mockery v2.7.5. DO NOT EDIT.

package saga

import (
	context "context"

	list "github.com/peteqproj/peteq/domain/list"
	mock "github.com/stretchr/testify/mock"
)

// MockListRepo is an autogenerated mock type for the ListRepo type
type MockListRepo struct {
	mock.Mock
}

// GetById provides a mock function with given fields: ctx, id
func (_m *MockListRepo) GetById(ctx context.Context, id string) (*list.List, error) {
	ret := _m.Called(ctx, id)

	var r0 *list.List
	if rf, ok := ret.Get(0).(func(context.Context, string) *list.List); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*list.List)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
