// Code generated by mockery v2.7.4. DO NOT EDIT.

package server

import (
	api "github.com/peteqproj/peteq/pkg/api"
	mock "github.com/stretchr/testify/mock"
)

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

// AddResource provides a mock function with given fields: r
func (_m *MockServer) AddResource(r api.Resource) error {
	ret := _m.Called(r)

	var r0 error
	if rf, ok := ret.Get(0).(func(api.Resource) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetReady provides a mock function with given fields:
func (_m *MockServer) SetReady() {
	_m.Called()
}

// Start provides a mock function with given fields:
func (_m *MockServer) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
