name: automation
tenant: user
root:
  resource: Automation
  database:
    name: automation_repo
    postgres:
      columns:
      - name: id
        type: text
        fromResource:
          as: string
          path: Metadata.ID
      - name: userid
        type: text
        fromTenant:
          as: string
          path: Metadata.ID
      - name: info
        type: json
        fromResource:
          as: string
          path: .
      indexes:
        - [userid]
      primeryKey: [id]
aggregates:
- resource: SensorBinding
  database:
    name: sensor_binding_repo
    postgres:
      columns:
      - name: id
        type: text
        fromResource:
          as: string
          path: Metadata.ID
      - name: userid
        type: text
        fromTenant:
          as: string
          path: Metadata.ID
      - name: automation
        type: text
        fromResource:
          path: Spec.Automation
          as: string
      - name: sensor
        type: text
        fromResource:
          path: Spec.Sensor
          as: string
      - name: info
        type: json
        fromResource:
          as: json
          path: .
      indexes:
        - [userid]
      uniqueIndexes:
        - [userid, sensor]
      primeryKey: [id]