apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5672
    name: postgres
    targetPort: 5672
  - port: 15672
    name: postgres-1
    targetPort: 15672
  - port: 5432
    name: postgres-2
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        env:
          - name: POSTGRES_DB
            value: awesomedb
          - name: POSTGRES_USER
            value: amazinguser
          - name: POSTGRES_PASSWORD
            value: perfectpassword
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
          name: postgres
        - containerPort: 15672
          name: postgres-1
        - containerPort: 5432
          name: postgres-2
