apiVersion: v1
kind: Service
metadata:
  name: postgres-client
spec:
  selector:
    app: postgres-client
  ports:
  - port: 8081
    name: web
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-client
spec:
  selector:
    matchLabels:
      app: postgres-client
  template:
    metadata:
      labels:
        app: postgres-client
    spec:
      containers:
      - name: postgres-client
        image: sosedoff/pgweb
        env:
          - name: DATABASE_URL
            value: postgres://amazinguser:perfectpassword@postgres:5432/awesomedb?sslmode=disable
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
          name: web
