/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CreateSensorAutomationBindingRequestBody struct for CreateSensorAutomationBindingRequestBody
type CreateSensorAutomationBindingRequestBody struct {
	Automation string `json:"automation"`
	Name       string `json:"name"`
	Sensor     string `json:"sensor"`
}

// NewCreateSensorAutomationBindingRequestBody instantiates a new CreateSensorAutomationBindingRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSensorAutomationBindingRequestBody(automation string, name string, sensor string) *CreateSensorAutomationBindingRequestBody {
	this := CreateSensorAutomationBindingRequestBody{}
	this.Automation = automation
	this.Name = name
	this.Sensor = sensor
	return &this
}

// NewCreateSensorAutomationBindingRequestBodyWithDefaults instantiates a new CreateSensorAutomationBindingRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSensorAutomationBindingRequestBodyWithDefaults() *CreateSensorAutomationBindingRequestBody {
	this := CreateSensorAutomationBindingRequestBody{}
	return &this
}

// GetAutomation returns the Automation field value
func (o *CreateSensorAutomationBindingRequestBody) GetAutomation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Automation
}

// GetAutomationOk returns a tuple with the Automation field value
// and a boolean to check if the value has been set.
func (o *CreateSensorAutomationBindingRequestBody) GetAutomationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Automation, true
}

// SetAutomation sets field value
func (o *CreateSensorAutomationBindingRequestBody) SetAutomation(v string) {
	o.Automation = v
}

// GetName returns the Name field value
func (o *CreateSensorAutomationBindingRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSensorAutomationBindingRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSensorAutomationBindingRequestBody) SetName(v string) {
	o.Name = v
}

// GetSensor returns the Sensor field value
func (o *CreateSensorAutomationBindingRequestBody) GetSensor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sensor
}

// GetSensorOk returns a tuple with the Sensor field value
// and a boolean to check if the value has been set.
func (o *CreateSensorAutomationBindingRequestBody) GetSensorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sensor, true
}

// SetSensor sets field value
func (o *CreateSensorAutomationBindingRequestBody) SetSensor(v string) {
	o.Sensor = v
}

func (o CreateSensorAutomationBindingRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["automation"] = o.Automation
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["sensor"] = o.Sensor
	}
	return json.Marshal(toSerialize)
}

type NullableCreateSensorAutomationBindingRequestBody struct {
	value *CreateSensorAutomationBindingRequestBody
	isSet bool
}

func (v NullableCreateSensorAutomationBindingRequestBody) Get() *CreateSensorAutomationBindingRequestBody {
	return v.value
}

func (v *NullableCreateSensorAutomationBindingRequestBody) Set(val *CreateSensorAutomationBindingRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSensorAutomationBindingRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSensorAutomationBindingRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSensorAutomationBindingRequestBody(val *CreateSensorAutomationBindingRequestBody) *NullableCreateSensorAutomationBindingRequestBody {
	return &NullableCreateSensorAutomationBindingRequestBody{value: val, isSet: true}
}

func (v NullableCreateSensorAutomationBindingRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSensorAutomationBindingRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
