/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// BacklogBacklogTaskList struct for BacklogBacklogTaskList
type BacklogBacklogTaskList struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewBacklogBacklogTaskList instantiates a new BacklogBacklogTaskList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBacklogBacklogTaskList() *BacklogBacklogTaskList {
	this := BacklogBacklogTaskList{}
	return &this
}

// NewBacklogBacklogTaskListWithDefaults instantiates a new BacklogBacklogTaskList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBacklogBacklogTaskListWithDefaults() *BacklogBacklogTaskList {
	this := BacklogBacklogTaskList{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BacklogBacklogTaskList) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacklogBacklogTaskList) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BacklogBacklogTaskList) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BacklogBacklogTaskList) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BacklogBacklogTaskList) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacklogBacklogTaskList) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BacklogBacklogTaskList) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BacklogBacklogTaskList) SetName(v string) {
	o.Name = &v
}

func (o BacklogBacklogTaskList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableBacklogBacklogTaskList struct {
	value *BacklogBacklogTaskList
	isSet bool
}

func (v NullableBacklogBacklogTaskList) Get() *BacklogBacklogTaskList {
	return v.value
}

func (v *NullableBacklogBacklogTaskList) Set(val *BacklogBacklogTaskList) {
	v.value = val
	v.isSet = true
}

func (v NullableBacklogBacklogTaskList) IsSet() bool {
	return v.isSet
}

func (v *NullableBacklogBacklogTaskList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBacklogBacklogTaskList(val *BacklogBacklogTaskList) *NullableBacklogBacklogTaskList {
	return &NullableBacklogBacklogTaskList{value: val, isSet: true}
}

func (v NullableBacklogBacklogTaskList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBacklogBacklogTaskList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
