/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// TaskTask struct for TaskTask
type TaskTask struct {
	Metadata *TaskMetadata `json:"metadata,omitempty"`
	Spec     *TaskSpec     `json:"spec,omitempty"`
}

// NewTaskTask instantiates a new TaskTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskTask() *TaskTask {
	this := TaskTask{}
	return &this
}

// NewTaskTaskWithDefaults instantiates a new TaskTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskTaskWithDefaults() *TaskTask {
	this := TaskTask{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *TaskTask) GetMetadata() TaskMetadata {
	if o == nil || o.Metadata == nil {
		var ret TaskMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskTask) GetMetadataOk() (*TaskMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *TaskTask) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given TaskMetadata and assigns it to the Metadata field.
func (o *TaskTask) SetMetadata(v TaskMetadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *TaskTask) GetSpec() TaskSpec {
	if o == nil || o.Spec == nil {
		var ret TaskSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskTask) GetSpecOk() (*TaskSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *TaskTask) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given TaskSpec and assigns it to the Spec field.
func (o *TaskTask) SetSpec(v TaskSpec) {
	o.Spec = &v
}

func (o TaskTask) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableTaskTask struct {
	value *TaskTask
	isSet bool
}

func (v NullableTaskTask) Get() *TaskTask {
	return v.value
}

func (v *NullableTaskTask) Set(val *TaskTask) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskTask) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskTask(val *TaskTask) *NullableTaskTask {
	return &NullableTaskTask{value: val, isSet: true}
}

func (v NullableTaskTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
