/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RegistrationRequestBody struct for RegistrationRequestBody
type RegistrationRequestBody struct {
	Email string `json:"email"`
	Password string `json:"password"`
}

// NewRegistrationRequestBody instantiates a new RegistrationRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationRequestBody(email string, password string) *RegistrationRequestBody {
	this := RegistrationRequestBody{}
	this.Email = email
	this.Password = password
	return &this
}

// NewRegistrationRequestBodyWithDefaults instantiates a new RegistrationRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationRequestBodyWithDefaults() *RegistrationRequestBody {
	this := RegistrationRequestBody{}
	return &this
}

// GetEmail returns the Email field value
func (o *RegistrationRequestBody) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegistrationRequestBody) GetEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegistrationRequestBody) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *RegistrationRequestBody) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegistrationRequestBody) GetPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegistrationRequestBody) SetPassword(v string) {
	o.Password = v
}

func (o RegistrationRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableRegistrationRequestBody struct {
	value *RegistrationRequestBody
	isSet bool
}

func (v NullableRegistrationRequestBody) Get() *RegistrationRequestBody {
	return v.value
}

func (v *NullableRegistrationRequestBody) Set(val *RegistrationRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationRequestBody(val *RegistrationRequestBody) *NullableRegistrationRequestBody {
	return &NullableRegistrationRequestBody{value: val, isSet: true}
}

func (v NullableRegistrationRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


