/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// TaskMetadata struct for TaskMetadata
type TaskMetadata struct {
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	Name string `json:"name"`
}

// NewTaskMetadata instantiates a new TaskMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskMetadata(id string, name string, ) *TaskMetadata {
	this := TaskMetadata{}
	this.Id = id
	this.Name = name
	return &this
}

// NewTaskMetadataWithDefaults instantiates a new TaskMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskMetadataWithDefaults() *TaskMetadata {
	this := TaskMetadata{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TaskMetadata) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskMetadata) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TaskMetadata) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TaskMetadata) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value
func (o *TaskMetadata) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TaskMetadata) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TaskMetadata) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TaskMetadata) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TaskMetadata) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TaskMetadata) SetName(v string) {
	o.Name = v
}

func (o TaskMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableTaskMetadata struct {
	value *TaskMetadata
	isSet bool
}

func (v NullableTaskMetadata) Get() *TaskMetadata {
	return v.value
}

func (v *NullableTaskMetadata) Set(val *TaskMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskMetadata(val *TaskMetadata) *NullableTaskMetadata {
	return &NullableTaskMetadata{value: val, isSet: true}
}

func (v NullableTaskMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


