/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SensorSensorCreateRequestBody struct for SensorSensorCreateRequestBody
type SensorSensorCreateRequestBody struct {
	Name string `json:"name"`
}

// NewSensorSensorCreateRequestBody instantiates a new SensorSensorCreateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSensorSensorCreateRequestBody(name string) *SensorSensorCreateRequestBody {
	this := SensorSensorCreateRequestBody{}
	this.Name = name
	return &this
}

// NewSensorSensorCreateRequestBodyWithDefaults instantiates a new SensorSensorCreateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSensorSensorCreateRequestBodyWithDefaults() *SensorSensorCreateRequestBody {
	this := SensorSensorCreateRequestBody{}
	return &this
}

// GetName returns the Name field value
func (o *SensorSensorCreateRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SensorSensorCreateRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SensorSensorCreateRequestBody) SetName(v string) {
	o.Name = v
}

func (o SensorSensorCreateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSensorSensorCreateRequestBody struct {
	value *SensorSensorCreateRequestBody
	isSet bool
}

func (v NullableSensorSensorCreateRequestBody) Get() *SensorSensorCreateRequestBody {
	return v.value
}

func (v *NullableSensorSensorCreateRequestBody) Set(val *SensorSensorCreateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSensorSensorCreateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSensorSensorCreateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSensorSensorCreateRequestBody(val *SensorSensorCreateRequestBody) *NullableSensorSensorCreateRequestBody {
	return &NullableSensorSensorCreateRequestBody{value: val, isSet: true}
}

func (v NullableSensorSensorCreateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSensorSensorCreateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
