/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ProjectsPopulatedProject struct for ProjectsPopulatedProject
type ProjectsPopulatedProject struct {
	Project *ProjectProject `json:"project,omitempty"`
	Tasks   *[]TaskTask     `json:"tasks,omitempty"`
}

// NewProjectsPopulatedProject instantiates a new ProjectsPopulatedProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectsPopulatedProject() *ProjectsPopulatedProject {
	this := ProjectsPopulatedProject{}
	return &this
}

// NewProjectsPopulatedProjectWithDefaults instantiates a new ProjectsPopulatedProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectsPopulatedProjectWithDefaults() *ProjectsPopulatedProject {
	this := ProjectsPopulatedProject{}
	return &this
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *ProjectsPopulatedProject) GetProject() ProjectProject {
	if o == nil || o.Project == nil {
		var ret ProjectProject
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsPopulatedProject) GetProjectOk() (*ProjectProject, bool) {
	if o == nil || o.Project == nil {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *ProjectsPopulatedProject) HasProject() bool {
	if o != nil && o.Project != nil {
		return true
	}

	return false
}

// SetProject gets a reference to the given ProjectProject and assigns it to the Project field.
func (o *ProjectsPopulatedProject) SetProject(v ProjectProject) {
	o.Project = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *ProjectsPopulatedProject) GetTasks() []TaskTask {
	if o == nil || o.Tasks == nil {
		var ret []TaskTask
		return ret
	}
	return *o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsPopulatedProject) GetTasksOk() (*[]TaskTask, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *ProjectsPopulatedProject) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given []TaskTask and assigns it to the Tasks field.
func (o *ProjectsPopulatedProject) SetTasks(v []TaskTask) {
	o.Tasks = &v
}

func (o ProjectsPopulatedProject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Project != nil {
		toSerialize["project"] = o.Project
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	return json.Marshal(toSerialize)
}

type NullableProjectsPopulatedProject struct {
	value *ProjectsPopulatedProject
	isSet bool
}

func (v NullableProjectsPopulatedProject) Get() *ProjectsPopulatedProject {
	return v.value
}

func (v *NullableProjectsPopulatedProject) Set(val *ProjectsPopulatedProject) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectsPopulatedProject) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectsPopulatedProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectsPopulatedProject(val *ProjectsPopulatedProject) *NullableProjectsPopulatedProject {
	return &NullableProjectsPopulatedProject{value: val, isSet: true}
}

func (v NullableProjectsPopulatedProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectsPopulatedProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
