/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SensorCreateRequestBody struct for SensorCreateRequestBody
type SensorCreateRequestBody struct {
	Name string `json:"name"`
}

// NewSensorCreateRequestBody instantiates a new SensorCreateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSensorCreateRequestBody(name string) *SensorCreateRequestBody {
	this := SensorCreateRequestBody{}
	this.Name = name
	return &this
}

// NewSensorCreateRequestBodyWithDefaults instantiates a new SensorCreateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSensorCreateRequestBodyWithDefaults() *SensorCreateRequestBody {
	this := SensorCreateRequestBody{}
	return &this
}

// GetName returns the Name field value
func (o *SensorCreateRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SensorCreateRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SensorCreateRequestBody) SetName(v string) {
	o.Name = v
}

func (o SensorCreateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSensorCreateRequestBody struct {
	value *SensorCreateRequestBody
	isSet bool
}

func (v NullableSensorCreateRequestBody) Get() *SensorCreateRequestBody {
	return v.value
}

func (v *NullableSensorCreateRequestBody) Set(val *SensorCreateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSensorCreateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSensorCreateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSensorCreateRequestBody(val *SensorCreateRequestBody) *NullableSensorCreateRequestBody {
	return &NullableSensorCreateRequestBody{value: val, isSet: true}
}

func (v NullableSensorCreateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSensorCreateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
