/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CreateAutomationRequestBody struct for CreateAutomationRequestBody
type CreateAutomationRequestBody struct {
	Name string `json:"name"`
}

// NewCreateAutomationRequestBody instantiates a new CreateAutomationRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAutomationRequestBody(name string) *CreateAutomationRequestBody {
	this := CreateAutomationRequestBody{}
	this.Name = name
	return &this
}

// NewCreateAutomationRequestBodyWithDefaults instantiates a new CreateAutomationRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAutomationRequestBodyWithDefaults() *CreateAutomationRequestBody {
	this := CreateAutomationRequestBody{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAutomationRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAutomationRequestBody) SetName(v string) {
	o.Name = v
}

func (o CreateAutomationRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateAutomationRequestBody struct {
	value *CreateAutomationRequestBody
	isSet bool
}

func (v NullableCreateAutomationRequestBody) Get() *CreateAutomationRequestBody {
	return v.value
}

func (v *NullableCreateAutomationRequestBody) Set(val *CreateAutomationRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAutomationRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAutomationRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAutomationRequestBody(val *CreateAutomationRequestBody) *NullableCreateAutomationRequestBody {
	return &NullableCreateAutomationRequestBody{value: val, isSet: true}
}

func (v NullableCreateAutomationRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAutomationRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
