/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ListList struct for ListList
type ListList struct {
	Metadata *ListMetadata `json:"metadata,omitempty"`
	Spec     *ListSpec     `json:"spec,omitempty"`
}

// NewListList instantiates a new ListList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListList() *ListList {
	this := ListList{}
	return &this
}

// NewListListWithDefaults instantiates a new ListList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListListWithDefaults() *ListList {
	this := ListList{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ListList) GetMetadata() ListMetadata {
	if o == nil || o.Metadata == nil {
		var ret ListMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListList) GetMetadataOk() (*ListMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ListList) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ListMetadata and assigns it to the Metadata field.
func (o *ListList) SetMetadata(v ListMetadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *ListList) GetSpec() ListSpec {
	if o == nil || o.Spec == nil {
		var ret ListSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListList) GetSpecOk() (*ListSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *ListList) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given ListSpec and assigns it to the Spec field.
func (o *ListList) SetSpec(v ListSpec) {
	o.Spec = &v
}

func (o ListList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableListList struct {
	value *ListList
	isSet bool
}

func (v NullableListList) Get() *ListList {
	return v.value
}

func (v *NullableListList) Set(val *ListList) {
	v.value = val
	v.isSet = true
}

func (v NullableListList) IsSet() bool {
	return v.isSet
}

func (v *NullableListList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListList(val *ListList) *NullableListList {
	return &NullableListList{value: val, isSet: true}
}

func (v NullableListList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
