/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// TriggerRunRequestBody struct for TriggerRunRequestBody
type TriggerRunRequestBody struct {
	Id string `json:"id"`
}

// NewTriggerRunRequestBody instantiates a new TriggerRunRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerRunRequestBody(id string, ) *TriggerRunRequestBody {
	this := TriggerRunRequestBody{}
	this.Id = id
	return &this
}

// NewTriggerRunRequestBodyWithDefaults instantiates a new TriggerRunRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerRunRequestBodyWithDefaults() *TriggerRunRequestBody {
	this := TriggerRunRequestBody{}
	return &this
}

// GetId returns the Id field value
func (o *TriggerRunRequestBody) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TriggerRunRequestBody) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TriggerRunRequestBody) SetId(v string) {
	o.Id = v
}

func (o TriggerRunRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableTriggerRunRequestBody struct {
	value *TriggerRunRequestBody
	isSet bool
}

func (v NullableTriggerRunRequestBody) Get() *TriggerRunRequestBody {
	return v.value
}

func (v *NullableTriggerRunRequestBody) Set(val *TriggerRunRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerRunRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerRunRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerRunRequestBody(val *TriggerRunRequestBody) *NullableTriggerRunRequestBody {
	return &NullableTriggerRunRequestBody{value: val, isSet: true}
}

func (v NullableTriggerRunRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerRunRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


