/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// TaskSpec struct for TaskSpec
type TaskSpec struct {
	DueDate *string `json:"dueDate,omitempty"`
}

// NewTaskSpec instantiates a new TaskSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskSpec() *TaskSpec {
	this := TaskSpec{}
	return &this
}

// NewTaskSpecWithDefaults instantiates a new TaskSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskSpecWithDefaults() *TaskSpec {
	this := TaskSpec{}
	return &this
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *TaskSpec) GetDueDate() string {
	if o == nil || o.DueDate == nil {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskSpec) GetDueDateOk() (*string, bool) {
	if o == nil || o.DueDate == nil {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *TaskSpec) HasDueDate() bool {
	if o != nil && o.DueDate != nil {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *TaskSpec) SetDueDate(v string) {
	o.DueDate = &v
}

func (o TaskSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DueDate != nil {
		toSerialize["dueDate"] = o.DueDate
	}
	return json.Marshal(toSerialize)
}

type NullableTaskSpec struct {
	value *TaskSpec
	isSet bool
}

func (v NullableTaskSpec) Get() *TaskSpec {
	return v.value
}

func (v *NullableTaskSpec) Set(val *TaskSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskSpec(val *TaskSpec) *NullableTaskSpec {
	return &NullableTaskSpec{value: val, isSet: true}
}

func (v NullableTaskSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


