/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// PkgApiApisAutomationCreateAutomationRequestBody struct for PkgApiApisAutomationCreateAutomationRequestBody
type PkgApiApisAutomationCreateAutomationRequestBody struct {
	Name string `json:"name"`
}

// NewPkgApiApisAutomationCreateAutomationRequestBody instantiates a new PkgApiApisAutomationCreateAutomationRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPkgApiApisAutomationCreateAutomationRequestBody(name string) *PkgApiApisAutomationCreateAutomationRequestBody {
	this := PkgApiApisAutomationCreateAutomationRequestBody{}
	this.Name = name
	return &this
}

// NewPkgApiApisAutomationCreateAutomationRequestBodyWithDefaults instantiates a new PkgApiApisAutomationCreateAutomationRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPkgApiApisAutomationCreateAutomationRequestBodyWithDefaults() *PkgApiApisAutomationCreateAutomationRequestBody {
	this := PkgApiApisAutomationCreateAutomationRequestBody{}
	return &this
}

// GetName returns the Name field value
func (o *PkgApiApisAutomationCreateAutomationRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PkgApiApisAutomationCreateAutomationRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PkgApiApisAutomationCreateAutomationRequestBody) SetName(v string) {
	o.Name = v
}

func (o PkgApiApisAutomationCreateAutomationRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullablePkgApiApisAutomationCreateAutomationRequestBody struct {
	value *PkgApiApisAutomationCreateAutomationRequestBody
	isSet bool
}

func (v NullablePkgApiApisAutomationCreateAutomationRequestBody) Get() *PkgApiApisAutomationCreateAutomationRequestBody {
	return v.value
}

func (v *NullablePkgApiApisAutomationCreateAutomationRequestBody) Set(val *PkgApiApisAutomationCreateAutomationRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePkgApiApisAutomationCreateAutomationRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePkgApiApisAutomationCreateAutomationRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePkgApiApisAutomationCreateAutomationRequestBody(val *PkgApiApisAutomationCreateAutomationRequestBody) *NullablePkgApiApisAutomationCreateAutomationRequestBody {
	return &NullablePkgApiApisAutomationCreateAutomationRequestBody{value: val, isSet: true}
}

func (v NullablePkgApiApisAutomationCreateAutomationRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePkgApiApisAutomationCreateAutomationRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
