/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SensorCreateRequestBody struct for SensorCreateRequestBody
type SensorCreateRequestBody struct {
	Cron        *string `json:"cron,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// NewSensorCreateRequestBody instantiates a new SensorCreateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSensorCreateRequestBody(name string) *SensorCreateRequestBody {
	this := SensorCreateRequestBody{}
	this.Name = name
	return &this
}

// NewSensorCreateRequestBodyWithDefaults instantiates a new SensorCreateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSensorCreateRequestBodyWithDefaults() *SensorCreateRequestBody {
	this := SensorCreateRequestBody{}
	return &this
}

// GetCron returns the Cron field value if set, zero value otherwise.
func (o *SensorCreateRequestBody) GetCron() string {
	if o == nil || o.Cron == nil {
		var ret string
		return ret
	}
	return *o.Cron
}

// GetCronOk returns a tuple with the Cron field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensorCreateRequestBody) GetCronOk() (*string, bool) {
	if o == nil || o.Cron == nil {
		return nil, false
	}
	return o.Cron, true
}

// HasCron returns a boolean if a field has been set.
func (o *SensorCreateRequestBody) HasCron() bool {
	if o != nil && o.Cron != nil {
		return true
	}

	return false
}

// SetCron gets a reference to the given string and assigns it to the Cron field.
func (o *SensorCreateRequestBody) SetCron(v string) {
	o.Cron = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SensorCreateRequestBody) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensorCreateRequestBody) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SensorCreateRequestBody) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SensorCreateRequestBody) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *SensorCreateRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SensorCreateRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SensorCreateRequestBody) SetName(v string) {
	o.Name = v
}

func (o SensorCreateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Cron != nil {
		toSerialize["cron"] = o.Cron
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSensorCreateRequestBody struct {
	value *SensorCreateRequestBody
	isSet bool
}

func (v NullableSensorCreateRequestBody) Get() *SensorCreateRequestBody {
	return v.value
}

func (v *NullableSensorCreateRequestBody) Set(val *SensorCreateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSensorCreateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSensorCreateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSensorCreateRequestBody(val *SensorCreateRequestBody) *NullableSensorCreateRequestBody {
	return &NullableSensorCreateRequestBody{value: val, isSet: true}
}

func (v NullableSensorCreateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSensorCreateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
