/*
 * Peteq API
 *
 * Peteq OpenAPI spec.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CreateRequestBody struct for CreateRequestBody
type CreateRequestBody struct {
	Name string `json:"name"`
}

// NewCreateRequestBody instantiates a new CreateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRequestBody(name string) *CreateRequestBody {
	this := CreateRequestBody{}
	this.Name = name
	return &this
}

// NewCreateRequestBodyWithDefaults instantiates a new CreateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRequestBodyWithDefaults() *CreateRequestBody {
	this := CreateRequestBody{}
	return &this
}

// GetName returns the Name field value
func (o *CreateRequestBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRequestBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRequestBody) SetName(v string) {
	o.Name = v
}

func (o CreateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateRequestBody struct {
	value *CreateRequestBody
	isSet bool
}

func (v NullableCreateRequestBody) Get() *CreateRequestBody {
	return v.value
}

func (v *NullableCreateRequestBody) Set(val *CreateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRequestBody(val *CreateRequestBody) *NullableCreateRequestBody {
	return &NullableCreateRequestBody{value: val, isSet: true}
}

func (v NullableCreateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
