apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
  namespace: rabbitmq
spec:
  replicas: 1
  service:
    type: LoadBalancer